### ISSUE TITLE
StreamsClient methods are not working

### ISSUE THREAD

**Issue by lowkay** [SymphonyPlatformSolutions/symphony-api-client-node#13]
Howdy,

Just tried using this and it appears as though the StreamsClient methods don't work.
I've tracked this down to the fact that the body of the request isn't written to the server => a non-existent "body" property is set in the https options, when it should be written using `request.write(data)`.

Additionally, the `getUserIMStreamId` needs to send a JSON array rather than an object of the form `{ userId }`.

Thanks!

**Comment by opoupeney** [comment]
This issue has been fixed and merged into the master branch.
