### ISSUE TITLE
getUserV3 creates url with 'emailList' instead of 'email'

### ISSUE THREAD

**Issue by karlmoll** [SymphonyPlatformSolutions/symphony-api-client-node#21]
getUserV3 produces an incorrect url per API docs when an email is passed:

https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/blob/c1bd1af2dcd47b8dee11c3493f214a854cf007ec/lib/UsersClient/index.js#L86

url param 'emailList' should be 'email'

**Comment by miguel-symphony** [comment]
`idList` should also be `uid`
https://rest-api.symphony.com/reference#users-lookup-v3

**Comment by mistryvinay** [comment]
Hi @karlmoll / @miguel-symphony thanks for raising this issue.  I have updated the code for searching for users.

To lookup an **individual** user using userID please use UsersClient.getUserFromIdV3.

The following API calls are to lookup **groups** of users,
UsersClient.getUsersFromEmailList
UsersClient.getUsersFromIdList

Which then use UsersClient.getUsersV3.
