### ISSUE TITLE
addMemberToRoom returning 415 Unsupported Media Type

### ISSUE THREAD

**Issue by karlmoll** [SymphonyPlatformSolutions/symphony-api-client-node#22]
After logging the request sent, and the header is being forced to be ’text/html’. It looks like the method is sending a form instead of application/json from JSON.stringify(body), but not positive.

<!doctype html><html lang="en"><head><title>HTTP Status 415 \'96 Unsupported Media Type</title><style type="text/css">h1 \{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;\} h2 \{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;\} h3 \{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;\} body \{font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;\} b \{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;\} p \{font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;\} a \{color:black;\} a.name \{color:black;\} .line \{height:1px;background-color:#525D76;border:none;\}</style></head><body><h1>HTTP Status 415 \'96 Unsupported Media Type</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Unsupported Media Type</p><p><b>Description</b> The origin server is refusing to service the request because the payload is in a form\
\

**Comment by mistryvinay** [comment]
@karlmoll / @miguel-symphony thank you for reporting this issue and identifying the problem.  Updates now included in the latest repo. Thanks again.
