### ISSUE TITLE
Using non-RSA, SymAuth logs the bots private key to console

### ISSUE THREAD

**Issue by miguel-symphony** [SymphonyPlatformSolutions/symphony-api-client-node#27]
When using non-RSA, private key is set in the 'options', which is logged to console on line 42
Should probably only log this if Symphony.setDebugMode = true.

https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/blob/a4c6a30f825a1deedd1666698799b2fb6f1cb71e/lib/SymBotAuth/index.js#L42

**Comment by mistryvinay** [comment]
This is now resolved as part of https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/pull/44
