### ISSUE TITLE
NTLM Auth

### ISSUE THREAD

**Issue by Bjego** [SymphonyPlatformSolutions/symphony-api-client-node#38]
Hey guys,

could you support corporate proxies with ntlm auth in your API client library? 
Setting  proxy values (url,username,password) in the proxy part in the config.json doesn't seem to work.

**Comment by symphony-elias** [comment]
Hello @Bjego,

Basic authentication with an http proxy works with version 1.1.2 of symphony-api-client-node. I tested it by specifying fields `"proxyURL"`, `"proxyUsername"` and `"proxyPassword"` in the config.json and with a [squid proxy](https://hub.docker.com/r/datadog/squid/).
We don't intend to support NTLM authentication any time soon.

Regards
