### ISSUE TITLE
getUserFromEmail seems not to handle error condition

### ISSUE THREAD

**Issue by barcarsul** [SymphonyPlatformSolutions/symphony-api-client-node#39]
I'm trying to test whether a user already exist based on email address.
If the user's email exists in Symphony then everything works fine. But if the user does not exist then I crash with an undefined: 1 error.

EXAMPLE CODE (I am authenticated and bot is hearing something):
//====================================					
//user does not exist, program fails with undefined:1
//====================================
var member = "fake.email@symphony.com";
var user =[];
Symphony.getUserFromEmail(member, true).then ( (user) => {
   console.log("fake email, nothing to show")
});	
//undefined: 1

//====================================					
//user exists, this works fine
//====================================
var member = "good.email@symphony.com";
var user = [];
Symphony.getUserFromEmail(member, true).then ( (user) => {
   console.log("UserID is: " + JSON.stringify(user.id))
});	
//UserID: 3123....123 <--correct userID

**Comment by mistryvinay** [comment]
Hi this issue was resolved as part of this PR https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/pull/40
