### ISSUE TITLE
Provide Flow and Typescript defintions

### ISSUE THREAD

**Issue by jonfreedman** [SymphonyPlatformSolutions/symphony-api-client-node#4]
It would be great if you could provide type definitions for [Flow](https://flow.org/en/) and [TypeScript](https://www.typescriptlang.org/).

**Comment by mmartinsky** [comment]
Opened PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46630 in DefinitelyTyped for this

**Comment by symphony-elias** [comment]
Implemented by @mmartinsky 
We will provide TS definitions in the version 2.0 of the lib.
