### ISSUE TITLE
Add docs for config.json

### ISSUE THREAD

**Issue by tomsugden** [SymphonyPlatformSolutions/symphony-api-client-node#5]
The code sample in the README passes a `config.json` file into an initialisation function, but doesn't seem to describe the schema for this file. It would be nice to add a bit of docs describing the file to avoid needing to reverse engineering it from various places in the code.

**Comment by tomsugden** [comment]
I found the relevant page in the Symphony Developer Guide, so have sent a pull-request: https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/pull/6

**Comment by opoupeney** [comment]
thank you @tomsugden for your contribution. Your PR has been merged into the master branch.
