### ISSUE TITLE
Pass bot config object instead of path

### ISSUE THREAD

**Issue by pkuca** [SymphonyPlatformSolutions/symphony-api-client-node#59]
Hi there,

Any plans to allow passing bot configuration via a straight javascript object instead of requiring the use of a file? While of course doable, there's a bit of extra complexity involved in having to mount the `config.json` with secrets into a docker container, especially when the file itself is just JSON.

**Comment by symphony-elias** [comment]
Hello @pkuca 

This has been implemented in #83 and #88.

Regards

**Comment by symphony-youri** [comment]
Covered by #99
