### ISSUE TITLE
Request response - JSON.parse error

### ISSUE THREAD

**Issue by binhnguyenfpt** [SymphonyPlatformSolutions/symphony-api-client-node#70]
Hi all.
I 'm member in FPT, we are using this lib for develop some feature.
I see a problem in this lib at file:
[https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/blob/master/lib/Request/index.js](https://github.com/SymphonyPlatformSolutions/symphony-api-client-node/blob/master/lib/Request/index.js)

code wrong at:
```
 defer.resolve(str === '' ? {} : JSON.parse(str))
```
when **`str`** is HTML content for cases: 
- 500- internal server error
- 502- bad gateway.

Please take a look.
Thanks!

**Comment by binhnguyenfpt** [comment]
This bug is being tracked in Jira ticket: https://perzoinc.atlassian.net/browse/PLAT-8708

**Comment by micaste** [comment]
The fix has been released in version 1.1.0. Could you try if this fixes your issue @binhnguyenfpt ?
