### ISSUE TITLE
Running symphony under API Management

### ISSUE THREAD

**Issue by ranjithsnair** [SymphonyPlatformSolutions/symphony-api-client-node#76]
I am trying to run symphony APIs using Azure API Management tool, All the APIs are now using the URL format https://api.company.com/symphony/proxy/v3/pod/...  https://api.company.com/symphony/proxy/v4/agent/...  etc.

There is no way I can put URL path prefix (Eg. /symphony/proxy) in the configuration. I have fixed in the SDK and done a pull request, path prefix is not mandatory but that field is useful when we are running behind a gateway.

**Comment by symphony-elias** [comment]
Hello @ranjithsnair 

This has been implemented in #83 and #88.

Regards
